### ISSUE TITLE
Zrušit /customers

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/kasa#74]
- [x] Zobrazení narozenin do /admin/customers - #72 
- [x] Testy pro zobrazení narozenin - #73 
- [x] Přesunout tlačítko pro nového zákazníka - #75
- [x] Testy pro tlačítko nového zákazníka - #76
- [x] Employee can view customer details - #98

**Comment by MichalBryxi** [comment]
Practically done.
